######################### BUILDER #########################

FROM node:12.14.1 as builder

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY ./ /app/

ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration

######################### FINAL #########################

FROM nginx:1.17.10-alpine

COPY --from=builder /app/dist/out/ /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
